<?php
$product = Mage::registry('current_product');
$manufacturerName = $product->getAttributeText('manufacturer');
$manufacturer = Mage::getModel('catalog/category')->loadByAttribute('name', $manufacturerName);

if ($manufacturer){
$image = $manufacturer->getImage();
if(!$image){
    $currentStore = Mage::app()->getStore()->getId();
    Mage::app()->getStore()->setId(Mage_Core_Model_App::ADMIN_STORE_ID);

    $image = Mage::getModel('catalog/category')->loadByAttribute('name', $manufacturerName)->getImage();

    Mage::app()->getStore()->setId($currentStore);
}
    ?>

    <a href="<?php echo $manufacturer->getUrl(); ?>">
        <?php if ($image && $image != 'no_selection') : ?>
            <div class="left manufacturer-info">
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)
                        . 'catalog/category/'
                        . $image; ?>" alt="<?php echo $manufacturer->getName(); ?>">
            </div>
        <?php endif; ?>
        <div class="left page-title manufacturer-info"><h2><?php echo $manufacturer->getName(); ?></h2>
        <hr class="product_descripton_hr">
        </div>
    </a>
    <br>
    <div class="clearboth"><?php echo $manufacturer->getDescription(); ?></div>
    <a href="<?php echo $manufacturer->getUrl(); ?>">
    <button type="button" class="btn btn-success"><?php echo $this->__('Shop more items from this brand'); ?></button>
    </a>

<?php }?>
