<?php if ($this->isActivePopUp()): ?>
<?php $contentType = $this->getContentType(); ?>
<div id="mteo_popup_bg_layer">
    <div id="mteo_popup_content">
        <?php if ($contentType == MT_Exitoffer_Model_Popup::CONTENT_TYPE_STATIC_CMS_BLOCK):?>
            <?php echo $this->getStaticBlockHtml(); ?>
        <?php else: ?>
            <?php echo $this->getPopupContentHtml(); ?>
        <?php endif; ?>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        exitOffer.init(<?php echo $this->getConfigJs(); ?>);
    });
</script>
<?php endif; ?>