<div class="checkbox-field">
<input
    name="<?php echo $this->getName();?>"
    type="checkbox"
    value="1"
    class="mteo-additional-field mteo-additional-field-<?php echo $this->getName();?> <?php echo $this->getIsRequired()?' mt-validator-required':''; ?>"
    data-field-name="<?php echo $this->getTitle()?>"
    id="mteo_additional_<?php echo $this->getName();?>"
    /><label for="mteo_additional_<?php echo $this->getName();?>"><?php echo $this->getTitle()?></label>
</div>