<?php $options = $this->getData('options');?>
<?php if (count($options) >= 2):?>
<?php  foreach ($options as $option): ?>
    <div class="checkbox-field radio-field">
        <input
            name="<?php echo $this->getName();?>"
            type="radio"
            value="<?php echo $option;?>"
            class="mteo-additional-field mteo-additional-field-<?php echo $this->getName();?> <?php echo $this->getIsRequired()?' mt-validator-required':''; ?>"
            data-field-name="<?php echo $this->getTitle()?>"
            id="mteo_additional_<?php echo $this->getName();?>"
            />
        <label for="mteo_additional_<?php echo $this->getName();?>"><?php echo $option;?></label>
    </div>
    <?php endforeach; ?>
<?php endif; ?>