<textarea
    class="mteo-additional-field mteo-additional-field-<?php echo $this->getName();?> <?php echo $this->getIsRequired()?' mt-validator-required':''; ?>"
    id="mteo_additional_<?php echo $this->getName();?>"
    data-field-name="<?php echo $this->getTitle()?>"
    onclick="if(this.value=='<?php echo $this->getTitle()?>') this.value=''" onblur="if(this.value=='') this.value='<?php echo $this->getTitle()?>'"
    name="<?php echo $this->getName();?>"><?php echo $this->getTitle()?></textarea>